services:
  nginx:
    build:
      context: .
      dockerfile: nginx/Dockerfile
    env_file:
      - .env
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "10"
    depends_on:
      - sparql-endpoint
    volumes:
      - ./data/${CATALOG_FILE}:/usr/share/nginx/html/catalog.rdf
    ports:
      - "0.0.0.0:${NGINX_PORT_HOST}:80"
      - "0.0.0.0:${NGINX_SSLPORT_HOST}:443"
    restart: on-failure:3

  sparql-endpoint:
    build:
      context: .
      dockerfile: easy-rdf-endpoint/Dockerfile.sparql
    env_file:
      - .env
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"
    volumes:
      - ./data/${CATALOG_FILE}:/app/data/catalog.rdf
    restart: on-failure:3

